# Generated by Django 4.2 on 2023-04-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
