# Generated by Django 4.2 on 2023-04-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='kvartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kvartera')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('number_rooms', models.IntegerField()),
                ('total_area', models.IntegerField()),
                ('living_space', models.IntegerField()),
                ('kitchen_area', models.PositiveIntegerField()),
                ('floor', models.PositiveIntegerField()),
                ('house_floor_plan', models.PositiveIntegerField()),
                ('year_of_construction', models.DateField()),
                ('furniture', models.CharField(choices=[('ha', 'ha'), ('yuq', 'yuq')], max_length=50)),
                ('vositachilik_haqi', models.CharField(choices=[('ha', 'ha'), ('yuq', 'yuq')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.repair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'verbose_name': 'kvartera',
                'verbose_name_plural': 'kvarteras',
            },
        ),
    ]
