# Generated by Django 4.2 on 2023-04-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_kvartera_furniture_remove_kvartera_repair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvartera',
            name='image',
        ),
    ]
