# Generated by Django 4.2 on 2023-04-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_kvartera_year_of_construction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvartera',
            name='category',
        ),
    ]
