# Generated by Django 4.2 on 2023-04-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_kvartera_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvartera',
            name='user',
        ),
    ]
