# Generated by Django 4.2 on 2023-04-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_kvartera_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartera',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is product available?'),
        ),
    ]
