# Generated by Django 4.2 on 2023-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_kvartera_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartera',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
