# Generated by Django 4.2 on 2023-04-07 16:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_kvartera_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvartera',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
