# Generated by Django 4.2 on 2023-04-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartera',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.category'),
            preserve_default=False,
        ),
    ]
