# Generated by Django 4.2 on 2023-04-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartera',
            name='image',
            field=models.ImageField(default=1, upload_to='kvartera'),
            preserve_default=False,
        ),
    ]
