# Generated by Django 4.2 on 2023-04-08 10:43

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_kvartera_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kvartera')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('addrees', models.TextField()),
                ('is_available', models.BooleanField(default=True, help_text='Is product available?')),
            ],
            options={
                'verbose_name': 'Student Work',
                'verbose_name_plural': 'Student Works',
            },
        ),
    ]
