# Generated by Django 4.2 on 2023-04-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_studentwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartera',
            name='addrees',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
