# Generated by Django 4.2 on 2023-04-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_user'),
        ('post', '0018_remove_kvartera_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartera',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
    ]
