# Generated by Django 4.2 on 2023-04-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_kvartera_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvartera',
            name='user',
        ),
    ]
